# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="schoolsofmagic" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="2.1.02" #mandatory

 # A display name for the mod
displayName="Schools of Magic: Second Semester" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="schools_of_magic_icon.png" #optional

# A text field displayed in the mod UI
credits="A special thank you to the mod developers who put time and effort into creating tutorials on youtube." #optional

# A text field displayed in the mod UI
authors="PaleImitations" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''

Congratulations on your acceptance to the Correspondence College of Witchcraft, a prestigious institute of mystical learning.

Please feel free to peruse at your pleasure, our core text, the Basic Arcana to begin your magical journey; craft an Apprentice's Wand; place a spell book atop a podium and learn some spells.

Do this and much more. This is only the beginning.


Warm regards,
Professor Hieronymus Evenere
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.schoolsofmagic]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.schoolsofmagic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
